### ISSUE TITLE
Problems ArduinoJson

### ISSUE THREAD

**Issue by usauerbrey** [AK-Homberger/NMEA2000WifiGateway-with-ESP32#2]
Hi
I have problems when trying to compile you NMEA-Gateway. 

Wifi-Serial-AP-AIS-CAN.ino: 413:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org\upgrade to learn how to upgrade your program to ArduinoJson version 6
   StaticJsonBuffer<800> jsonBuffer

Any solution/recommendation?

Best Regards Uwe

**Comment by AndrasSzep** [comment]
Hi Uwe,

Actually I only forked the library from
AK-Homberger/NMEA2000WifiGateway-with-ESP32 and used only to develop
my own apps.
If you describe what you want perhaps I can give you some hints.

Kind regards,

------------------
András Szép
andras.szep@gmail.com
UK: +44 - 7824 35 9474


------------------
András Szép
andras.szep@gmail.com
UK: +44 - 7824 35 9474

**Comment by AK-Homberger** [comment]
Did you install the JSON library version 5?

**Comment by AndrasSzep** [comment]
I have ArduinoJSON 6.15.2 installed on my comp, but not sure if I ever used
It yet.
I have an app publishing NMEA2000 messages in NMEA0183 format as a TCP
stream. This can be used by OpenCPN.
Also just made the other way around - translating NMEA0183 messages from a
TCP stream into NMEA2000 bus.

------------------
András Szép
andras.szep@gmail.com
UK: +44 - 7824 35 9474

**Comment by usauerbrey** [comment]
I was able to install ArduinoJSON 5 instead of ArduinoJSON 6. I was not aware, that this is posslible.
So now it woks, even so it is not perfect, not using the latest libriries.

**Comment by AK-Homberger** [comment]
You have to use JSON version 5 not 6. Then it should work.

> Am 15.06.2020 um 13:21 schrieb AndrasSzep <notifications@github.com>:
> 
> ﻿
> I have ArduinoJSON 6.15.2 installed on my comp, but not sure if I ever used
> It yet.
> I have an app publishing NMEA2000 messages in NMEA0183 format as a TCP
> stream. This can be used by OpenCPN.
> Also just made the other way around - translating NMEA0183 messages from a
> TCP stream into NMEA2000 bus.
> 
> ------------------
> András Szép
> andras.szep@gmail.com
> UK: +44 - 7824 35 9474
> 
>

**Comment by AK-Homberger** [comment]
Now the code works with ArduinoJSON verion 6.
