### ISSUE TITLE
generic SSID because of too short password

### ISSUE THREAD

**Issue by leifnagtegaal** [AK-Homberger/NMEA2000WifiGateway-with-ESP32#5]
Hi, thank you for your nice work.
I found a little Issue.
The password for the AP mode must at least use a minimum of 8 char. 
Otherwise the method call WiFi.softAP(AP_ssid, AP_password); will fail and it give a generic SSID (e.g. ESP_32_83A4H) without password.

**Comment by svdrummer** [comment]
This is because the standard is 8 Chrs

**Comment by AK-Homberger** [comment]
That's the standard behaviour of the ESP32. And I don't think its's a problem.

**Comment by leifnagtegaal** [comment]
Yes, you are right, but in the source code of this project there is used a 7 Char password.
So maybe other users will get in trouble with this.

**Comment by AK-Homberger** [comment]
The password should be anyway replaced with a own unique on. But I will add this to the documentation.
